//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuby.Properties {
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Drawing;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    var temp = new ResourceManager("Zuby.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }
        

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }

            set {
                resourceCulture = value;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ColumnHeader_Filtered {
            get {
                var obj = ResourceManager.GetObject("ColumnHeader_Filtered", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ColumnHeader_FilteredAndOrderedASC {
            get {
                var obj = ResourceManager.GetObject("ColumnHeader_FilteredAndOrderedASC", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ColumnHeader_FilteredAndOrderedDESC {
            get {
                var obj = ResourceManager.GetObject("ColumnHeader_FilteredAndOrderedDESC", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ColumnHeader_OrderedASC {
            get {
                var obj = ResourceManager.GetObject("ColumnHeader_OrderedASC", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ColumnHeader_OrderedDESC {
            get {
                var obj = ResourceManager.GetObject("ColumnHeader_OrderedDESC", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ColumnHeader_SavedFilters {
            get {
                var obj = ResourceManager.GetObject("ColumnHeader_SavedFilters", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ColumnHeader_UnFiltered {
            get {
                var obj = ResourceManager.GetObject("ColumnHeader_UnFiltered", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MenuStrip_OrderASCbool {
            get {
                var obj = ResourceManager.GetObject("MenuStrip_OrderASCbool", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MenuStrip_OrderASCnum {
            get {
                var obj = ResourceManager.GetObject("MenuStrip_OrderASCnum", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MenuStrip_OrderASCtxt {
            get {
                var obj = ResourceManager.GetObject("MenuStrip_OrderASCtxt", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MenuStrip_OrderDESCbool {
            get {
                var obj = ResourceManager.GetObject("MenuStrip_OrderDESCbool", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MenuStrip_OrderDESCnum {
            get {
                var obj = ResourceManager.GetObject("MenuStrip_OrderDESCnum", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MenuStrip_OrderDESCtxt {
            get {
                var obj = ResourceManager.GetObject("MenuStrip_OrderDESCtxt", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MenuStrip_ResizeGrip {
            get {
                var obj = ResourceManager.GetObject("MenuStrip_ResizeGrip", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SearchToolBar_ButtonCaseSensitive {
            get {
                var obj = ResourceManager.GetObject("SearchToolBar_ButtonCaseSensitive", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SearchToolBar_ButtonClose {
            get {
                var obj = ResourceManager.GetObject("SearchToolBar_ButtonClose", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SearchToolBar_ButtonFromBegin {
            get {
                var obj = ResourceManager.GetObject("SearchToolBar_ButtonFromBegin", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SearchToolBar_ButtonSearch {
            get {
                var obj = ResourceManager.GetObject("SearchToolBar_ButtonSearch", resourceCulture);
                return (Bitmap)obj;
            }
        }
        

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SearchToolBar_ButtonWholeWord {
            get {
                var obj = ResourceManager.GetObject("SearchToolBar_ButtonWholeWord", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}
